/**
 * Parser and Sanitizer for AI Brand Visibility Reports generated by the monitoring engine.
 */

export interface ParsedVisibilityReport {
  title: string;
  visibilityScore?: number;
  summaryText?: string;
  recommendation?: string;
  engineBreakdown: string[];
  wins: string[];
  promptsNeedingWork: string[];
  shareOfVoice: string[];
  citedOn: string[];
  answersShowedUp: Array<{
    prompt: string;
    engineAndCountry: string;
    mentionStatus: string;
    snippet: string;
    fullAnswer: string;
  }>;
  cleanMarkdown: string;
}

/**
 * Removes external Apify / platform links to keep reports proprietary and clean.
 */
export function cleanApifyReportMarkdown(markdown: string): string {
  if (!markdown) return '';
  return markdown
    // Remove ## Links section completely
    .replace(/## Links[\s\S]*?(?=(# 📊|## |---|$))/gi, '')
    // Remove any leftover direct Apify links
    .replace(/-?\s*🗂\s*\*\*Apify dataset:\*\*.*?\n/gi, '')
    .replace(/-?\s*▶︎\s*\*\*This run:\*\*.*?\n/gi, '')
    .replace(/-?\s*🔗\s*\*\*Your visibility page:\*\*.*?\n/gi, '')
    .replace(/Apify dataset:\s*https?:\/\/[^\s\n]+/gi, '')
    .replace(/Run:\s*[A-Za-z0-9]+/gi, '')
    .replace(/https:\/\/api\.apify\.com[^\s\n)]+/gi, '')
    .replace(/https:\/\/console\.apify\.com[^\s\n)]+/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/**
 * Extracts structured sections from the markdown report.
 */
export function parseVisibilityReport(markdown: string): ParsedVisibilityReport {
  const clean = cleanApifyReportMarkdown(markdown);

  let title = '';
  const titleMatch = clean.match(/^#\s+(.+)$/m);
  if (titleMatch) {
    title = titleMatch[1].replace(/—\s*AI Visibility Report.*/i, '').trim();
  }

  let visibilityScore: number | undefined;
  const scoreMatch = clean.match(/visibility\s*score:\s*(\d+)/i);
  if (scoreMatch && scoreMatch[1]) {
    visibilityScore = parseInt(scoreMatch[1], 10);
  }

  let recommendation = '';
  const recMatch = clean.match(/>\s*🎯\s*(?:This week:\s*)?([^\n]+)/i);
  if (recMatch && recMatch[1]) {
    recommendation = recMatch[1].trim();
  }

  let summaryText = '';
  const summaryMatch = clean.match(/Your brand appeared in[^\n]+/i);
  if (summaryMatch) {
    summaryText = summaryMatch[0].trim();
  }

  // Section extractors
  const extractListItems = (sectionHeaderRegex: RegExp): string[] => {
    const match = clean.match(sectionHeaderRegex);
    if (!match || match.index === undefined) return [];
    const rest = clean.slice(match.index + match[0].length);
    const nextSectionIndex = rest.search(/(^##\s+|^---)/m);
    const sectionContent = nextSectionIndex !== -1 ? rest.slice(0, nextSectionIndex) : rest;
    return sectionContent
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('-') || line.startsWith('*') || line.startsWith('•'))
      .map((line) => line.replace(/^[-*•]\s*/, '').trim())
      .filter(Boolean);
  };

  const engineBreakdown = extractListItems(/##\s+📺\s*By engine/i);
  const wins = extractListItems(/##\s+🏆\s*New wins/i);
  const promptsNeedingWork = extractListItems(/##\s+🔧\s*Prompts needing work/i);
  const shareOfVoice = extractListItems(/##\s+⚔️\s*Share of voice[^\n]*/i);
  const citedOn = extractListItems(/##\s+✅\s*You're cited on/i);

  // Parse "Where your brand showed up" items
  const answersShowedUp: Array<{
    prompt: string;
    engineAndCountry: string;
    mentionStatus: string;
    snippet: string;
    fullAnswer: string;
  }> = [];

  const whereSectionMatch = clean.match(/##\s+✅\s*Where your brand showed up/i);
  if (whereSectionMatch && whereSectionMatch.index !== undefined) {
    const whereContent = clean.slice(whereSectionMatch.index + whereSectionMatch[0].length);
    const itemChunks = whereContent.split(/^###\s+/m).filter(Boolean);

    for (const chunk of itemChunks) {
      const lines = chunk.split('\n').map((l) => l.trim()).filter(Boolean);
      if (lines.length === 0) continue;

      const headerLine = lines[0];
      const headerParts = headerLine.split('—');
      const prompt = headerParts[0].replace(/^["']|["']$/g, '').trim();
      const engineAndCountry = headerParts.slice(1).join('—').trim();

      let mentionStatus = '';
      let snippet = '';
      let fullAnswer = '';

      for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        if (line.startsWith('> ✅') || line.startsWith('> ❌') || line.startsWith('✅') || line.startsWith('❌')) {
          mentionStatus = line.replace(/^[>\s]+/, '').trim();
        } else if (line.startsWith('> …') || (line.startsWith('>') && !snippet && !line.includes('📄'))) {
          snippet = line.replace(/^[>\s]+/, '').trim();
        } else if (line.startsWith('> 📄') || line.includes('While the vast') || fullAnswer.length > 0) {
          const cleanLine = line.replace(/^[>\s📄]+/, '').trim();
          fullAnswer += (fullAnswer ? ' ' : '') + cleanLine;
        } else if (!snippet) {
          snippet = line.replace(/^[>\s]+/, '').trim();
        }
      }

      if (prompt) {
        answersShowedUp.push({
          prompt,
          engineAndCountry: engineAndCountry || 'AI Search Engine',
          mentionStatus: mentionStatus || 'Named in the answer',
          snippet: snippet || fullAnswer.slice(0, 200) || 'Mention verified in answer stream.',
          fullAnswer: fullAnswer || snippet,
        });
      }
    }
  }

  return {
    title: title || 'AI Visibility Report',
    visibilityScore,
    summaryText,
    recommendation,
    engineBreakdown,
    wins,
    promptsNeedingWork,
    shareOfVoice,
    citedOn,
    answersShowedUp,
    cleanMarkdown: clean,
  };
}
