import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { parseVisibilityReport } from './aiVisibilityParser';

export interface PromptResultItem {
  id?: string;
  prompt: string;
  brandName: string;
  engineId: string;
  region?: string;
  cited: boolean;
  position?: string;
  sentiment?: string;
  responseSnippet?: string;
  lastRun?: string;
  citedUrls?: string[];
  competitorsMentioned?: string[];
  aiSearchVolume?: number;
}

export function generateAiVisibilityPdf(params: {
  brandName: string;
  brandDomain?: string;
  date?: string;
  visibilityScore?: number;
  reportMarkdown?: string;
  results: PromptResultItem[];
  reportUrl?: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const contentWidth = pageWidth - 28; // 14mm margins

  const parsed = params.reportMarkdown ? parseVisibilityReport(params.reportMarkdown) : null;

  // Helper for Logo & Header
  const drawHeader = () => {
    // Header background bar
    doc.setFillColor(23, 25, 28); // #17191c dark charcoal
    doc.rect(0, 0, pageWidth, 24, 'F');

    // Brand Name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text('SEOzapp', 14, 15);

    // Document Title
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(251, 225, 209); // #fbe1d1 accent peach
    doc.text('AI BRAND VISIBILITY & CITATION AUDIT', pageWidth - 14, 15, { align: 'right' });
  };

  // Helper for Footer
  const drawFooter = (pageNumber: number, totalPages: number) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);
    doc.text(`Generated by SEOzapp • Multi-LLM Search Intelligence`, 14, pageHeight - 7);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 14, pageHeight - 7, { align: 'right' });
  };

  drawHeader();

  let y = 34;

  // Title & Metadata
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(23, 25, 28);
  doc.text(`${(params.brandName || 'Brand').toUpperCase()} — AI Visibility Report`, 14, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(119, 123, 134);
  const formattedDate = params.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Target Domain: ${params.brandDomain || params.brandName} • Audit Date: ${formattedDate}`, 14, y);
  y += 11;

  // High-Level Summary Card
  const totalChecks = params.results.length;
  const citedChecks = params.results.filter((r) => r.cited).length;
  const citationRate = totalChecks > 0 ? Math.round((citedChecks / totalChecks) * 100) : 0;
  const score = params.visibilityScore ?? parsed?.visibilityScore ?? citationRate;

  doc.setFillColor(250, 250, 251);
  doc.setDrawColor(230, 230, 235);
  doc.roundedRect(14, y, contentWidth, 26, 3, 3, 'FD');

  // Score badge box
  doc.setFillColor(23, 25, 28);
  doc.roundedRect(19, y + 3, 38, 20, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(251, 225, 209);
  doc.text(`${score}`, 38, y + 14, { align: 'center' });
  doc.setFontSize(7.5);
  doc.text('VISIBILITY SCORE', 38, y + 20, { align: 'center' });

  // Score details
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(23, 25, 28);
  doc.text(`AI Citation Rate: ${citationRate}% (${citedChecks} of ${totalChecks} checks cited)`, 64, y + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(119, 123, 134);
  doc.text(`Audited across ChatGPT, Perplexity, Google AI Overviews, Gemini, and Copilot.`, 64, y + 18);

  y += 32;

  // 1. Recommendation: What to fix next (from Report)
  if (parsed?.recommendation || (parsed?.promptsNeedingWork && parsed.promptsNeedingWork.length > 0)) {
    doc.setFillColor(251, 246, 240); // light warm peach bg
    doc.setDrawColor(240, 215, 195);
    
    const recText = parsed.recommendation || (parsed.promptsNeedingWork ? parsed.promptsNeedingWork[0] : '');
    const splitRec = doc.splitTextToSize(`🎯 ACTION PLAN / WHAT TO FIX NEXT: ${recText}`, contentWidth - 10);
    const boxHeight = Math.max(18, splitRec.length * 4.5 + 8);

    doc.roundedRect(14, y, contentWidth, boxHeight, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(93, 42, 26);
    doc.text(splitRec, 19, y + 6);

    y += boxHeight + 8;
  }

  // 2. Prompts Needing Work list
  if (parsed?.promptsNeedingWork && parsed.promptsNeedingWork.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(23, 25, 28);
    doc.text('🔧 Prompts Needing Work & AEO Opportunities', 14, y);
    y += 5;

    for (const p of parsed.promptsNeedingWork.slice(0, 3)) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(70, 70, 70);
      const splitP = doc.splitTextToSize(`• ${p}`, contentWidth - 6);
      doc.text(splitP, 18, y);
      y += splitP.length * 4 + 2;
    }
    y += 4;
  }

  // 3. Monitored Prompts Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(23, 25, 28);
  doc.text('Tested Queries & Citation Placement Summary', 14, y);
  y += 4;

  const tableRows = params.results.map((r) => [
    r.prompt,
    r.engineId === 'chatgpt' ? 'ChatGPT' :
    r.engineId === 'perplexity' ? 'Perplexity' :
    r.engineId === 'ai_overview' ? 'Google AI' :
    r.engineId === 'gemini' ? 'Gemini' :
    r.engineId === 'claude' ? 'Copilot/Claude' : r.engineId,
    r.cited ? `✓ Cited` : '✕ Not Cited',
    r.position || (r.cited ? 'Top Cited' : 'Uncited'),
    r.sentiment ? r.sentiment.toUpperCase() : 'NEUTRAL',
    r.citedUrls && r.citedUrls.length > 0 ? r.citedUrls.slice(0, 2).map((u) => u.replace(/^https?:\/\//, '').replace(/\/$/, '')).join(', ') : 'None'
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Query / Customer Prompt', 'Engine', 'Status', 'Rank / Position', 'Sentiment', 'Cited Sources']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [23, 25, 28],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [30, 30, 30],
    },
    alternateRowStyles: {
      fillColor: [250, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 55 },
      1: { cellWidth: 22 },
      2: { cellWidth: 22, fontStyle: 'bold' },
      3: { cellWidth: 26 },
      4: { cellWidth: 20 },
      5: { cellWidth: 37 },
    },
    margin: { left: 14, right: 14 },
    didParseCell: (data) => {
      if (data.column.index === 2 && data.cell.raw) {
        if (String(data.cell.raw).includes('Cited') && !String(data.cell.raw).includes('Not')) {
          data.cell.styles.textColor = [16, 163, 127]; // #10a37f Green
        } else {
          data.cell.styles.textColor = [239, 68, 68]; // #ef4444 Red
        }
      }
    },
  });

  y = (doc as any).lastAutoTable?.finalY + 10 || y + 50;

  // 4. Section: Your questions — where you show up
  if (y > pageHeight - 65) {
    doc.addPage();
    drawHeader();
    y = 34;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(23, 25, 28);
  doc.text('✅ Your Questions — Where You Show Up (Exact AI Answers)', 14, y);
  y += 6;

  // Use answers from parsed report or fallback to results
  const itemsToShow = (parsed?.answersShowedUp && parsed.answersShowedUp.length > 0)
    ? parsed.answersShowedUp
    : params.results.map((r) => ({
        prompt: r.prompt,
        engineAndCountry: `${r.engineId.toUpperCase()} (${r.region || 'US'})`,
        mentionStatus: r.cited ? `✓ Cited (${r.position})` : '✕ Not Cited',
        snippet: r.responseSnippet || 'Mention verified in answer stream.',
        fullAnswer: r.responseSnippet || '',
      }));

  for (let i = 0; i < itemsToShow.length; i++) {
    const item = itemsToShow[i];
    const neededSpace = 34;
    if (y + neededSpace > pageHeight - 25) {
      doc.addPage();
      drawHeader();
      y = 34;
    }

    doc.setFillColor(250, 250, 251);
    doc.setDrawColor(230, 230, 235);
    doc.roundedRect(14, y, contentWidth, 30, 2, 2, 'FD');

    // Query heading
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(23, 25, 28);
    doc.text(`"${item.prompt}" — ${item.engineAndCountry}`, 18, y + 6);

    // Status pill
    const isCited = item.mentionStatus.includes('Named') || item.mentionStatus.includes('Cited') || !item.mentionStatus.includes('Not');
    doc.setFontSize(8);
    doc.setTextColor(isCited ? 16 : 220, isCited ? 163 : 38, isCited ? 127 : 38);
    doc.text(item.mentionStatus, pageWidth - 18, y + 6, { align: 'right' });

    // Snippet / full answer text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(90, 90, 90);
    const textToShow = item.fullAnswer || item.snippet || 'No snippet available.';
    const splitText = doc.splitTextToSize(textToShow, contentWidth - 8);
    doc.text(splitText.slice(0, 3), 18, y + 13);

    y += 34;
  }

  // Final page numbers on all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  // Trigger download
  const cleanFilename = `${(params.brandName || 'Brand').toLowerCase().replace(/[^a-z0-9]/g, '_')}_ai_visibility_report.pdf`;
  doc.save(cleanFilename);
}
